// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// ── Android ──────────────────────────────────────────────────────────────
  /// Project:  smart-trolly-bd454
  /// App ID:   1:538094337834:android:9b3fe74da60d90ff93a853
  /// Package:  com.example.smart_trolly
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDskpOX-Z75blI8tXMVcG9oe_UsaR-v-IM',
    appId: '1:538094337834:android:9b3fe74da60d90ff93a853',
    messagingSenderId: '538094337834',
    projectId: 'smart-trolly-bd454',
    storageBucket: 'smart-trolly-bd454.firebasestorage.app',
    authDomain: 'smart-trolly-bd454.firebaseapp.com',
  );

  /// ── iOS / macOS ──────────────────────────────────────────────────────────
  /// NOTE: Add an iOS app in the Firebase console if you need iOS support,
  /// then replace these values with your iOS google-services-info.plist values.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDskpOX-Z75blI8tXMVcG9oe_UsaR-v-IM',
    appId: '1:538094337834:ios:9b3fe74da60d90ff93a853', // Placeholder, needs actual iOS App ID
    messagingSenderId: '538094337834',
    projectId: 'smart-trolly-bd454',
    storageBucket: 'smart-trolly-bd454.firebasestorage.app',
    authDomain: 'smart-trolly-bd454.firebaseapp.com',
    iosBundleId: 'com.example.smartTrolly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDskpOX-Z75blI8tXMVcG9oe_UsaR-v-IM',
    appId: '1:538094337834:ios:9b3fe74da60d90ff93a853', // Placeholder
    messagingSenderId: '538094337834',
    projectId: 'smart-trolly-bd454',
    storageBucket: 'smart-trolly-bd454.firebasestorage.app',
    authDomain: 'smart-trolly-bd454.firebaseapp.com',
    iosBundleId: 'com.example.smartTrolly',
  );

  /// ── Web ──────────────────────────────────────────────────────────────────
  /// Add a Web app in Firebase console → Project Settings → Your apps
  /// to get the real web appId and authDomain values.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDskpOX-Z75blI8tXMVcG9oe_UsaR-v-IM',
    appId: '1:538094337834:web:9b3fe74da60d90ff93a853', // Placeholder
    messagingSenderId: '538094337834',
    projectId: 'smart-trolly-bd454',
    storageBucket: 'smart-trolly-bd454.firebasestorage.app',
    authDomain: 'smart-trolly-bd454.firebaseapp.com',
  );

  /// ── Windows ──────────────────────────────────────────────────────────────
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDskpOX-Z75blI8tXMVcG9oe_UsaR-v-IM',
    appId: '1:538094337834:web:9b3fe74da60d90ff93a853', // Placeholder
    messagingSenderId: '538094337834',
    projectId: 'smart-trolly-bd454',
    storageBucket: 'smart-trolly-bd454.firebasestorage.app',
    authDomain: 'smart-trolly-bd454.firebaseapp.com',
  );
}
